"""empty message

Revision ID: 80d328f7b9c6
Revises: 
Create Date: 2020-10-31 11:10:46.437517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d328f7b9c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('ip', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=37), nullable=False),
    sa.Column('body', sa.String(length=100), nullable=True),
    sa.Column('optionOne', sa.String(length=30), nullable=True),
    sa.Column('optionTwo', sa.String(length=30), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('answeredOne', sa.Integer(), nullable=True),
    sa.Column('answeredTwo', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.ip'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_body'), 'questions', ['body'], unique=True)
    op.create_index(op.f('ix_questions_timestamp'), 'questions', ['timestamp'], unique=False)
    op.create_table('middle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.ip'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('middle')
    op.drop_index(op.f('ix_questions_timestamp'), table_name='questions')
    op.drop_index(op.f('ix_questions_body'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('users')
    # ### end Alembic commands ###
